name: Teams Notification

on:
  push:
    branches:
      - main

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: Send notification to Teams
        uses: chgeuer/github-action-microsoft-teams-notification@v1.0.0
        with:
          webhook-uri: ${{ secrets.TEAMS_WEBHOOK_URL }}
          title: 'GitHub Action Run'
          summary: 'A new push has been made to the main branch.'
          text: 'Repository: ${{ github.repository }} | Commit: ${{ github.sha }}'
          color: '0078D4' # This is Microsoft's blue color
