name: Teams Notification

on:
  push:
    branches:
      - main

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: Send notification to Teams
        uses: echapmanFromBunnings/msteams-connector-webhook@2.0.3
        with:
          webhook: ${{ secrets.TEAMS_WEBHOOK_URL }}
          message: 'Hello world. This is a slug... &#x1F41B;'
