name: build
on:
  pull_request:

jobs:
  testJob:
  runs-on: ubuntu-latest
  steps:
    - uses: actions/checkout@v3
    - run: |
        exit 0
  build:
    name: Checkout and notify
    needs: [TestJob]
    if: ${{always()}}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v1
      - uses: freezer00/teams-webhook-action@v1.4.1
        with:
          webhook_url: ${{secrets.MS_WEBHOOK_URL}}
          needs: ${{ toJson(needs) }}
          job: ${{ toJson(job) }}
          title: Custom title
          additional_button_title: |-
            Link to Google
            Link to Microsoft
          additional_button_url: |-
            https://google.com
            https://www.microsoft.com/de-de/microsoft-teams
          hide_facts: false
          dry_run: false
