    name: Teams Notification Workflow

    on: [push]

    jobs:
      build:
        runs-on: ubuntu-latest
        steps:
          - name: Checkout code
            uses: actions/checkout@v4

          - name: Send Teams notification
            uses: actions/microsoft-teams-webhook-message-bot@v1 # Example action
            with:
              webhookUri: ${{ secrets.MS_TEAMS_WEBHOOK_URL }}
              message: "GitHub Actions workflow run completed for ${{ github.repository }} on branch ${{ github.ref_name }}!"
              # You can also use 'adaptiveCard' for more complex messages
