name: Send Adaptive Card to Teams

on:
  push:
    branches:
      - main

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - uses: neonidian/teams-notify-build-status@v3
        with:
          webhookUrl: ${{ secrets.MS_TEAMS_WEBHOOK_URL }}
          message: Workflow run passed !!
