name: Send Adaptive Card to Teams

on:
  push:
    branches:
      - main

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: Send Adaptive Card to Teams
        env:
          WEBHOOK_URL: ${{ secrets.TEAMS_WEBHOOK_URL }}
        run: |
          CARD='{
    "type": "message",
    "attachments": [
        {
            "contentType": "application/vnd.microsoft.card.adaptive",
            "contentUrl": null,
            "content": {
                "$schema": "https://adaptivecards.io/schemas/adaptive-card.json",
                "type": "AdaptiveCard",
                "version": "1.5",
                "body": [
                    {
                        "type": "ColumnSet",
                        "columns": [
                            {
                                "type": "Column",
                                "width": "auto",
                                "items": [
                                    {
                                        "type": "Image",
                                        "style": "Person",
                                        "url": "https://github.githubassets.com/assets/GitHub-Mark-ea2971cee799.png",
                                        "altText": "Github Logo",
                                        "height": "36px",
                                        "width": "27px"
                                    }
                                ]
                            },
                            {
                                "type": "Column",
                                "verticalContentAlignment": "Center",
                                "width": "stretch",
                                "items": [
                                    {
                                        "type": "TextBlock",
                                        "weight": "Bolder",
                                        "text": "EQRS Github Action",
                                        "color": "Accent",
                                        "wrap": true,
                                        "size": "Large"
                                    }
                                ]
                            }
                        ]
                    },
                    {
                        "type": "Container",
                        "style": "attention",
                        "bleed": true,
                        "items": [
                            {
                                "type": "FactSet",
                                "facts": [
                                    {
                                        "title": "Build:",
                                        "value": "$GITHUB_REF"
                                    },
                                    {
                                        "title": "Status:",
                                        "value": "WORKING ON THIS!"
                                    },
                                    {
                                        "title": "Author:",
                                        "value": "<at>$GITHUB_ACTOR</at>"
                                    }
                                ]
                            }
                        ]
                    }
                ],
                "actions": [
                    {
                        "type": "Action.OpenUrl",
                        "title": "View Build",
                        "url": "https://github.com/GITHUB_REPOSITORY/actions/runs/$GITHUB_RUN_ID"
                    }
                ],
                "msteams": {
                    "entities": [
                        {
                            "type": "mention",
                            "text": "<at>Jeremy Page</at>",
                            "mentioned": {
                                "id": "43211@icf.com",
                                "name": "Jeremy Page"
                            }
                        }
                    ]
                }
            }
        }
    ]
}'
          curl -H "Content-Type: application/json" -d "$CARD" "$WEBHOOK_URL"
