name: Teams Notification

on:
  push:
    branches:
      - main

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: Send Notification To Teams Channel
        uses: a-kumar5/python-teams-notification-action@v0.2.0-alpha
        with:
          url: ${{ secrets.TEAMS_WEBHOOK_URL }}
          content: "pymsnotify sent this message from github actions."
          title: "HELLO_TEAMS"
