name: Send Adaptive Card to Teams - test

on:
  push:
    branches:
      - main

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: Send Adaptive Card to Teams
        env:
          WEBHOOK_URL: ${{ secrets.MS_TEAMS_WEBHOOK_URL }}
        run: |
          CARD='{
            "$schema": "http://adaptivecards.io/schemas/adaptive-card.json",
            "type": "AdaptiveCard",
            "version": "1.4",
            "body": [
              {
                "type": "TextBlock",
                "text": "Test number 15!!",
                "weight": "Bolder",
                "size": "Medium"
              }
            ]
          }'
          curl -H "Content-Type: application/json" -d "$CARD" "$WEBHOOK_URL"