name: workflow1

on: [push]

jobs: 
  run-github-actions:
    runs-on: ubuntu-latest
    steps:
      - name: Say hi to papa
        id: chocolate
        uses: actions/hello-world-javascript-action@v1
        with:
          who-to-greet: Jeremy
      - name: Log Greeting Time
        run: echo ${{ steps.chocolate.outputs.time }}
